services:
  app:
    build: ./backend
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    volumes:
#      - ./backend/src:/app/src
      - ~/.m2:/root/.m2
    develop:
      watch:
        - path: ./backend/pom.xml
          action: rebuild
        - path: ./backend/src
          action: rebuild